## **Librerias y Dependencias**

In [22]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# **Parte I - 5p**
a) Realizar una tabla con los valores medidos para las temperaturas del agua fría ($𝑇_1$), del
agua caliente ($𝑇_2$) y de la mezcla ($𝑇_𝑚$), así como los volúmenes empleados, para los
tres ensayos.  
b) Determinar la incertidumbre con la que se han obtenido las temperaturas y los
volúmenes empleados.  
c) Obtener la fórmula para el valor de K y calcular dicho valor para cada uno de los
ensayos.  
d) Hallar la fórmula para el error de K  
e) Calcular dicho error para cada uno de los ensayos.

## _a) Datos_

In [23]:
datos = {
    "T Fria (T_1)":[21,21,21],
    "T Caliente (T_2)": [55,56,57],
    "T Mezcla (T_m)": [36,37,37]
}

m = 239.25 # En g ± 0.05
V = 100 # en ml ± 1
rho = 1 # en g/cm^3
M =  rho*V # g M_1 = M_2

err_V = 1 # ml
err_T = 0.5 # ºC
err_m = 0.05 # en g
err_rho = 0.01 # en g/cm^3 = ml

In [24]:
df_datos = pd.DataFrame(datos)
df_datos

   T Fria (T_1)  T Caliente (T_2)  T Mezcla (T_m)
0            21                55              36
1            21                56              37
2            21                57              37

## _b) Incertidumbres de T y V_

In [25]:
print(f"V = {V} ± {err_V}ml\n")

for i in range(len(df_datos)):
    T1 = df_datos.loc[i, "T Fria (T_1)"]
    T2 = df_datos.loc[i, "T Caliente (T_2)"]
    Tm = df_datos.loc[i, "T Mezcla (T_m)"]
    
    print(f"Experimento {i+1}:")
    print(f"  T1 = {T1} ± {err_T}°C")
    print(f"  T2 = {T2} ± {err_T}°C")
    print(f"  Tm = {Tm} ± {err_T}°C\n")

V = 100 ± 1ml

Experimento 1:
  T1 = 21 ± 0.5°C
  T2 = 55 ± 0.5°C
  Tm = 36 ± 0.5°C

Experimento 2:
  T1 = 21 ± 0.5°C
  T2 = 56 ± 0.5°C
  Tm = 37 ± 0.5°C

Experimento 3:
  T1 = 21 ± 0.5°C
  T2 = 57 ± 0.5°C
  Tm = 37 ± 0.5°C

## _c) Formula y Valor de K_

$Q_{cedido}=Q_{absorbido}$

$(M_1c + K)(T_m-T_1) = M_2c(T_2 - T_m) \rightarrow (M_1c + K) = \frac{M_2c(T_2 - T_m)}{(T_m-T_1)} \rightarrow K = \frac{M_2c(T_2 - T_m)}{(T_m-T_1)} - M_1c$

In [26]:
c = 1 # cal/g ºC

K_formula = lambda m1,m2,c,t2,t1,tm: (m2*c*(t2-tm))/(tm - t1) - (m1*c)

df_datos["K"] = None

for i in range(len(df_datos)):
    T1 = df_datos.loc[i, "T Fria (T_1)"]
    T2 = df_datos.loc[i, "T Caliente (T_2)"]
    Tm = df_datos.loc[i, "T Mezcla (T_m)"]

    K = K_formula(M,M,c,T2,T1,Tm)

    df_datos.loc[i, "K"] = K

    print(f"Experimento {i+1}:")
    print(f"K = {K}g")

Experimento 1:
K = 26.66666666666667g
Experimento 2:
K = 18.75g
Experimento 3:
K = 25.0g

In [27]:
df_datos

   T Fria (T_1)  T Caliente (T_2)  T Mezcla (T_m)          K
0            21                55              36  26.666667
1            21                56              37      18.75
2            21                57              37       25.0

### _d) Formula Error K_

$M = \frac{\rho}{V} \rightarrow (\delta M)^2 = (\delta \rho)^2 + (\delta V)^2 \rightarrow (\frac{\Delta M}{M})^2 = (\frac{\Delta \rho}{\rho})^2 + (\frac{\Delta V}{V})^2 \rightarrow \Delta M = M \sqrt{(\frac{\Delta \rho}{\rho})^2 + (\frac{\Delta V}{V})^2}$

In [28]:
err_M = M * np.sqrt((err_rho/rho)**2 + (err_V/V)**2)
print(f"M = {M} ± {err_M:.3f}g")

M = 100 ± 1.414g

$(ΔK)^2= (\frac{∂K}{​∂T_1}​\Delta T_1​)^2+(\frac{∂K}{​∂T_2}​\Delta T_2​)^2+(\frac{∂K}{​∂T_m}​\Delta T_m​)^2+(\frac{∂K}{​∂M_1}​\Delta M_1​)^2+(\frac{∂K}{​∂M_2}​\Delta M_2​)^2$



$\frac{∂K}{​∂T_1} = \frac{M_2c (T_2 - T_m)}{(T_m - T_1)^2}$    
  
$\frac{∂K}{​∂T_2} = \frac{M_2c}{T_m - T_1}$  
  
$\frac{∂K}{​∂T_m} = \frac{-M_2c(T_2 - T_1)}{(T_m - T_1)^2}$  
  
$\frac{∂K}{​∂M_1} = -c$  

$\frac{∂K}{​∂M_2} = \frac{c(T_2 - T_m)}{T_m - T_1}$

In [29]:
dK_dT1 = lambda t1,t2,tm: (M*c*(t2-tm))/(tm-t1)**2
dK_dT2 = lambda t1,tm: (M*c)/(tm-t1)
dK_dTm = lambda t1,t2,tm: (-M*c*(t2-t1))/(tm-t1)**2
dK_dM1 = -c
dK_dM2 = lambda t1,t2,tm: (c*(t2-tm))/(tm - t1)

In [30]:
for i in range(len(df_datos)):
    T1 = df_datos.loc[i, "T Fria (T_1)"]
    T2 = df_datos.loc[i, "T Caliente (T_2)"]
    Tm = df_datos.loc[i, "T Mezcla (T_m)"]

    err_T1 = dK_dT1(T1,T2,Tm) * err_T
    err_T2 = dK_dT2(T1,Tm) * err_T
    err_Tm = dK_dTm(T1,T2,Tm) * err_T
    err_M1 = dK_dM1 * err_M
    err_M2 = dK_dM2(T1,T2,Tm) * err_M

    print(f"Experimento {i+1}")
    print(f"Error en T1: {err_T1}")
    print(f"Error en T2: {err_T2}")
    print(f"Error en Tm: {err_Tm}")
    print(f"Error en M1: {err_M1}")
    print(f"Error en M2: {err_M2}\n")

Experimento 1
Error en T1: 4.222222222222222
Error en T2: 3.3333333333333335
Error en Tm: -7.555555555555555
Error en M1: -1.4142135623730951
Error en M2: 1.7913371790059205

Experimento 2
Error en T1: 3.7109375
Error en T2: 3.125
Error en Tm: -6.8359375
Error en M1: -1.4142135623730951
Error en M2: 1.6793786053180504

Experimento 3
Error en T1: 3.90625
Error en T2: 3.125
Error en Tm: -7.03125
Error en M1: -1.4142135623730951
Error en M2: 1.7677669529663689

$(ΔK)^2= (\frac{M_2c (T_2 - T_m)}{(T_m - T_1)^2}​\Delta T_1​)^2+(\frac{M_2c}{T_m - T_1}​\Delta T_2​)^2+(\frac{-M_2c(T_2 - T_1)}{(T_m - T_1)^2}​\Delta T_m​)^2
+(-c​\Delta M_1​)^2+(\frac{c(T_2 - T_m)}{T_m - T_1}​\Delta M_2​)^2$

In [31]:
err_K_formula = lambda t1,t2,tm: np.sqrt(
    (dK_dT1(T1,T2,Tm) * err_T)**2 +
    (dK_dT2(T1,Tm) * err_T)**2 +
    (dK_dTm(T1,T2,Tm) * err_T)**2 +
    (dK_dM1 * err_M)**2 +
    (dK_dM2(T1,T2,Tm) * err_M)**2
)

### _e) Calcular error de K_

In [32]:
for i in range(len(df_datos)):
    T1 = df_datos.loc[i, "T Fria (T_1)"]
    T2 = df_datos.loc[i, "T Caliente (T_2)"]
    Tm = df_datos.loc[i, "T Mezcla (T_m)"]
    K =  df_datos.loc[i, "K"]

    err_K = err_K_formula(T1,T2,Tm)

    df_datos.loc[i, "err_K"] = err_K

    print(f"Experimento {i+1}:")
    print(f"K = {K} ± {err_K:.3f}g")

Experimento 1:
K = 26.66666666666667 ± 9.552g
Experimento 2:
K = 18.75 ± 8.665g
Experimento 3:
K = 25.0 ± 8.921g

## *Parte 2 - 2p*
A partir de los valores anteriores, obtener la media ponderada de K junto con su error

$\bar{K} = \frac{\sum_{i=1}^n \frac{K_i}{(\Delta K_i)^2}}{\sum_{i=1}^n \frac{1}{(\Delta K_i)^2}} ± \frac{1}{\sqrt{\sum_{i=1}^n \frac{1}{(\Delta K_i)^2}}}$

In [33]:
sum_num = 0
sum_den = 0


for i in range(len(df_datos)):
    K =  df_datos.loc[i, "K"]
    err_K = df_datos.loc[i, "err_K"]

    sum_num += K/err_K**2
    sum_den += 1/err_K**2

In [34]:
media_K = sum_num/sum_den
err_media_K = 1 / np.sqrt(sum_den)

print(f"Media K = {media_K:.3f} ± {err_media_K:.3f}g")

Media K = 23.237 ± 5.210g

## **Parte 3 - 2p**
A partir del valor de K obtenido en el apartado anterior y de la masa del calorímetro, hallar la capacidad calorífica de éste junto con su error.

$c = \frac{\bar{K}}{m_{cal}}$

In [35]:
c = media_K / m

err_c = c * np.sqrt((err_media_K/media_K)**2+(err_m/m)**2)

print(f"c={c:.3f} ± {err_c:.3f} cal/g ºC")

c=0.097 ± 0.022 cal/g ºC